Encapsulate all DateTimeFormat calls to work around Chrome bug
Chrome (49.0.2623.75 used in testing, but reported from some newer
versions as well) doesn't deal well with new timezones added to Windows:
https://blogs.technet.microsoft.com/dst2007/2016/06/02/introducing-new-windows-time-zones/

Ocassionally when `new Intl.DateTimeFormat()` is called without being
given an explicit timezone, it will error out with:

    RangeError: Unsupported time zone specified undefined

Since there's nothing we can do about this right now, simply ignore the
error and hope that Chrome is going to fix this in the future.